.\" Manpage for git-refresh
.TH man 1 "November 2019" "1.0" "git refresh man page"
.SH NAME
git refresh \- Rebase a local branch against a remote branch.
.SH SYNOPSIS
git refresh [-r|remote=<name>] [-b|--branch=<name>]
.SH DESCRIPTION
Cleanly rebase a local working branch on a remote branch.
Defaults to origin/master.
.SH OPTIONS
.TP
.I [-r|--remote]
The name of the git remote.
.I [-b|--branch=<name>]
The name of the remote branch to rebase against.
.SH BUGS
No known bugs.
.SH AUTHOR
Shelley Vohr <shelley.vohr@gmail.com>