.\" Manpage for git-patch-out
.TH man 1 "November 2019" "1.0" "git patch-out man page"
.SH NAME
git patch-out \- Quickly export a diff to another location.
.SH SYNOPSIS
git patch-out <file_location> <filename>
.SH DESCRIPTION
Allow a user to quickly export a diff
in patch format to another location. Defaults to Desktop.
.SH OPTIONS
.TP
.I <file_location>
The location on disk to export the diff.
.I  <filename>
The filename for the exported diff.
.SH BUGS
No known bugs.
.SH AUTHOR
Shelley Vohr <shelley.vohr@gmail.com>