.\" Manpage for git-sync
.TH man 1 "November 2019" "1.0" "git sync man page"
.SH NAME
git refresh \- Update your origin from an upstream branch.
.SH SYNOPSIS
git sync <upstream>
.SH DESCRIPTION
Fetch latest commits from an upstream branch and update your origin
with those commits.
.SH OPTIONS
.TP
.I <upstream>
The name of your upstream git remote.
.SH BUGS
No known bugs.
.SH AUTHOR
Shelley Vohr <shelley.vohr@gmail.com>