.\" Manpage for git-patch-apply
.TH man 1 "November 2019" "1.0" "git patch-apply man page"
.SH NAME
git patch-apply \- Apply a remote commit.
.SH SYNOPSIS
git patch-apply <commit_url>
.SH DESCRIPTION
Apply a patch to your current working branch from
a remote commit url.
.SH OPTIONS
.TP
.I <commit_url>
The url for the commit to apply to your current working branch
.SH BUGS
No known bugs.
.SH AUTHOR
Shelley Vohr <shelley.vohr@gmail.com>