#!/usr/bin/env zsh
set -e

: '
git patch-out [-l|--location=<path>] [-n|--name=<name>] [--a|--append]

Allow a user to quickly dump a diff
in patch format to their desktop.
'

# set patch location to user input or default to ~/Desktop
PATCH_LOCATION="$HOME/Desktop"

# set patch name to user input or default to local_diff
PATCH_NAME="local_diff"

# handle user flags
for i in "$@"
do
case $i in
  -l=*|--location=*)
  PATCH_LOCATION="${i#*=}"
  ;;
  -n=*|--name=*)
  PATCH_NAME="${i#*=}"
  ;;
  -a|--append)
  APPEND=1
  ;;
  *)
  echo "Unknown argument: $i" && exit 1
  ;;
esac
done

# redirect diff and either append or replace in file at chosen location
if [ $APPEND == 1 ]
then
   git diff --full-index HEAD > $PATCH_LOCATION/$PATCH_NAME.patch
else
   git diff --full-index HEAD >> $PATCH_LOCATION/$PATCH_NAME.patch
fi
