#!/usr/bin/env zsh
set -e

: '
git tack <file_name>

A quick way to add a forgotten change to the most recent commit
in a branch without needing to create a new one for a trivial 
change. Automatically pushes to the current branch.
'

# get current branch
branch="$(git branch | grep \* | cut -d ' ' -f2)"

# choose what file(s) to stage
if [ "$#" -eq 1 ]; then
# allow the user to only stage specific files
  git add $1
else
# if no files passed, stage all recently changed files
  git add .
fi

# amend the previous commit with no changes to commit msg
git commit --amend --no-edit

## force push the changes (with lease!)
git push --force-with-lease origin $branch
