#!/usr/bin/env zsh
set -e

: '
git patch-out <file_location> <file_name>

Allow a user to quickly dump a diff
in patch format to their desktop.
'

# choose what file(s) to stage
if [ "$#" -gt 2 ]; then
  echo 'Error: this command takes 2 arguments - filename and output location.'
  exit 1
fi

# set patch location to user input or default to ~/Desktop
PATCH_LOCATION=${1:-"$HOME/Desktop"}

# set patch name to user input or default to local_diff
PATCH_NAME=${2:-"local_diff"}

# get changes to all tracked files and then redirect
# output to a patch at desired location
git diff --full-index HEAD > $PATCH_LOCATION/$PATCH_NAME.patch
