#!/usr/bin/env bash

set -e

: '
git get-fork-branch remote:branch

Check out a branch from an arbitrary fork.
'

# The fork remote name.
REMOTE=""

# The name of the branch to check out.
BRANCH=""

# shellcheck disable=SC2068
read -r REMOTE BRANCH <<< "$(IFS=":"; echo $@)"

# Bail if missing required arguments.
if [ -z "$REMOTE" ] || [ -z "$BRANCH" ]
then
  echo "Error: remote and branch arguments are required" && exit 1
fi

# Fetch the current repo name.
REPO_NAME=$(basename "$(git remote get-url origin)")

# Fetch branch from user's remote.
git fetch git@github.com:"$REMOTE/$REPO_NAME".git "$BRANCH:$BRANCH"

# Switch to new branch.
git checkout "$BRANCH"