#!/usr/bin/env bash
# shellcheck disable=SC2063

set -e

: '
git tack [-f|--filepath=<path>]

A quick way to add a forgotten change to the most recent commit
in a branch without needing to create a new one for a trivial 
change. Automatically pushes to the current branch.
'

# The current checked-out branch.
CURRENT_BRANCH="$(git branch | grep \* | cut -d ' ' -f2)"

# The files to stage.
STAGED="."

# Parse user arguments.
for i in "$@"
do
case $i in
  -f=*|--filepath=*)
  STAGED="${i#*=}"
  ;;
  *)
  echo "Unknown argument: $i" && exit 1
  ;;
esac
done

# Stage all specified files.
git add "$STAGED"

# Amend the previous commit with no changes to commit message.
git commit --amend --no-edit

# Force push the changes (with lease!).
git push --force-with-lease origin "$CURRENT_BRANCH"
