#!/usr/bin/env bash

set -e

: '
git patch-apply [-u|--url=<url>]

Apply a patch to your current working branch from
a remote commit url.
'

# The url to pull the patch from. 
URL=""

for i in "$@"
do
case $i in
  -u=*|--url=*)
  URL="${i#*=}"
  ;;
  *)
  echo "Unknown argument: $i" && exit 1
  ;;
esac
done

# Bail if no url is set.
if [ -z "$URL" ]
then
  echo "Error: url argument is required" && exit 1
fi

# Apply patch with fallback to 3-way merge.
git am --3way --whitespace=fix < "$(curl -L "$URL".patch)"
