#!/usr/bin/env bash

set -e

: '
git sync [-u|--upstream=<name>] [-o|--origin=<name>]

Fetch latest commits from an upstream remote branch and update your origin
with those commits.
'

# The name of the upstream remote.
UPSTREAM="upstream"

# The name of the origin remote.
ORIGIN="origin"

# Parse user arguments.
for i in "$@"
do
case $i in
  -u=*|--upstream=*)
  UPSTREAM="${i#*=}"
  ;;
  -o=*|--origin=*)
  ORIGIN="${i#*=}"
  ;;
  *)
  echo "Unknown argument: $i" && exit 1
  ;;
esac
done

if CURRENT_BRANCH=$(git symbolic-ref --short -q HEAD)
then
  # Fetch latest upstream commit sha.
  git fetch "$UPSTREAM" "$CURRENT_BRANCH"

  # Rebase local branch against latest upstream sha.
  git rebase "$UPSTREAM/$CURRENT_BRANCH"

  # Update origin with latest upstream commit sha.
  git push "$ORIGIN" "$CURRENT_BRANCH"
else
  echo 'Error: Cannot get current branch'
fi