#!/usr/bin/env bash

set -e

: '
git patch-out [-l|--location=<path>] [-n|--name=<name>] [--a|--append]

Allow a user to quickly dump a diff
in patch format to their desktop.
'

# Whether to append to or overwrite the generated patchfile.
APPEND_TO_FILE=0

# The location to output the patchfile.
PATCH_LOCATION="$HOME/Desktop"

# The name of the patchfile.
PATCH_NAME="local_diff"

# Parse user arguments.
for i in "$@"
do
case $i in
  -l=*|--location=*)
  PATCH_LOCATION="${i#*=}"
  ;;
  -n=*|--name=*)
  PATCH_NAME="${i#*=}"
  ;;
  -a|--append)
  APPEND_TO_FILE=1
  ;;
  *)
  echo "Unknown argument: $i" && exit 1
  ;;
esac
done

# Redirect diff and either append or replace in file at chosen location.
if [ "$APPEND_TO_FILE" -eq 0 ]
then
   git diff --full-index HEAD > "$PATCH_LOCATION/$PATCH_NAME.patch"
else
   git diff --full-index HEAD >> "$PATCH_LOCATION/$PATCH_NAME.patch"
fi
