.\" Manpage for git-tack
.TH man 1 "November 2019" "1.0" "git tack man page"
.SH NAME
git tack \- Add a forgotten change to the most recent commit in a branch.
.SH SYNOPSIS
git tack [-f|--filepath=<path>]
.SH DESCRIPTION
A quick way to add a forgotten change to the most recent commit
in a branch without needing to create a new commit.
Automatically pushes to the current branch.
.SH OPTIONS
.TP
.I [-f|--filepath=<path>]
The path to the file to stage and add to the last commit.
.SH BUGS
No known bugs.
.SH AUTHOR
Shelley Vohr <shelley.vohr@gmail.com>