.\" Manpage for git-get-fork-branch
.TH man 1 "September 2020" "1.0" "git get-fork-branch man page"
.SH NAME
git get-fork-branch \- Check out a branch from an arbitrary fork.
.SH SYNOPSIS
git get-fork-branch remote:branch
.SH DESCRIPTION
Fetch and check out a branch from an arbitrary fork for local testing.
.SH OPTIONS
.TP
.I [remote:branch]
The remote and branch to check out, e.g. @codebytere:patch-1.
.SH BUGS
No known bugs.
.SH AUTHOR
Shelley Vohr <shelley.vohr@gmail.com>