.\" Manpage for git-sync
.TH man 1 "November 2019" "1.0" "git sync man page"
.SH NAME
git refresh \- Update your origin from an upstream branch.
.SH SYNOPSIS
git sync [-u|--upstream=<upstream>] [-o|--origin=<origin>]
.SH DESCRIPTION
Fetch latest commits from an upstream branch and update your origin
with those commits.
.SH OPTIONS
.TP
.I [-u|--upstream=<upstream>]
The name of the upstream git remote. Defaults to 'upstream'.
.I [-o|--origin=<origin>]
The name of the origin git remote. Defaults to 'origin'.
.SH BUGS
No known bugs.
.SH AUTHOR
Shelley Vohr <shelley.vohr@gmail.com>