.\" Manpage for git-get-fork-branch
.TH man 1 "September 2020" "1.0" "git get-fork-branch man page"
.SH NAME
git get-fork-branch \- Check out a branch from an arbitrary fork.
.SH SYNOPSIS
git get-fork-branch [-u|--username=<username>] [-b|--branch=<branch>]
.SH DESCRIPTION
Fetch and check out a branch from an arbitrary fork for local testing.
.SH OPTIONS
.TP
.I [-u|--username=<username>]
The username of the user whose fork you want to check out a branch from.
.I [-b|--branch=<branch>]
The name of the remote branch to check out.
.SH BUGS
No known bugs.
.SH AUTHOR
Shelley Vohr <shelley.vohr@gmail.com>