.\" Manpage for git-refresh
.TH man 1 "November 2019" "1.0" "git refresh man page"
.SH NAME
git refresh \- Rebase a local branch against a remote branch.
.SH SYNOPSIS
git refresh [-r|remote=<remote>] [-b|--branch=<branch>]
.SH DESCRIPTION
Cleanly rebase a local working branch on a remote branch.
.SH OPTIONS
.TP
.I [-r|--remote=<remote>]
The name of the git remote. Defaults to 'origin'.
.I [-b|--branch=<branch>]
The name of the remote branch to rebase against. Defaults to 'master'.
.SH BUGS
No known bugs.
.SH AUTHOR
Shelley Vohr <shelley.vohr@gmail.com>