.\" Manpage for git-patch-out
.TH man 1 "November 2019" "1.0" "git patch-out man page"
.SH NAME
git patch-out \- Quickly export a diff to another location.
.SH SYNOPSIS
git patch-out [-l|--location=<path>] [-n|--name=<name>] [--a|--append]
.SH DESCRIPTION
Allow a user to quickly export a diff in patch format to a file at a chosen location.
.SH OPTIONS
.TP
.I [-l|--location=<path>]
The location on disk where the file will be created. Defaults to '$HOME/Desktop'.
.I  [-n|--name=<name>]
The name of the file to create or append to. Defaults to 'local_diff'.
.I  [--a|--append]
Append to the file instead of overwriting it.
.SH BUGS
No known bugs.
.SH AUTHOR
Shelley Vohr <shelley.vohr@gmail.com>