.\" Manpage for git-patch-apply
.TH man 1 "November 2019" "1.0" "git patch-apply man page"
.SH NAME
git patch-apply \- Apply a remote commit.
.SH SYNOPSIS
git patch-apply [-u|--url=<url>]
.SH DESCRIPTION
Apply a patch from a remote commit url to your current working branch.
.SH OPTIONS
.TP
.I [-u|--url=<url>]
The url for the commit to apply to your current working branch.
.SH BUGS
No known bugs.
.SH AUTHOR
Shelley Vohr <shelley.vohr@gmail.com>